export const BDProducts = [
    {
        id: "prod-bambu-natural",
        name: "Banco Bambú Natural",
        price: 1200000,
        compareAtPrice: 1000000,
        category: "detalles",
        categoryLabel: "Detalles que Cuentan",
        summary: "Banco en bambú con tapizado y estante inferior, estilo nórdico.",
        summaryDiscount: "¡20% OFF! Banco en bambú nórdico por tiempo limitado.",
        description: "Fabricado en bambú natural con acabado cálido y textura orgánica. Tiene una silueta ligera, estante inferior funcional y tapizado neutro para sumar carácter a entradas, vestieres o rincones decorativos.",
        material: "Bambú natural + tapizado",
        style: "Nórdico / Orgánico",
        storage: "Estante inferior",
        idealFor: "Entrada · Dormitorio · Vestier",
        guarantee: "12 meses",
        featured: true,
        discount: true,
        stock: 7,
        images: [
            "../../assets/img/catalogo/card-venta1.jpg",
            "../../assets/img/catalogo/card-venta2.jpg",
            "../../assets/img/catalogo/card-venta3.jpg",
            "../../assets/img/catalogo/card-venta4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/banner-venta.jpg"
    },
    {
        id: "prod-sofa-azul",
        name: "Sofá moderno de 2 puestos azul",
        price: 1500000,
        compareAtPrice: 1200000,
        category: "sala",
        categoryLabel: "Sala & Descanso",
        summary: "Sofá azul de 2 puestos, cómodo, moderno y con cojines amplios.",
        summaryDiscount: "¡25% OFF! Sofá azul moderno con precio especial.",
        description: "Sofá de dos puestos con diseño contemporáneo, líneas limpias y cojines generosos. Su tela azul suave y patas en madera lo convierten en una pieza protagonista para salas serenas y elegantes.",
        material: "Madera + tela",
        style: "Moderno / Contemporáneo / Minimalista",
        storage: "No incluye almacenamiento",
        idealFor: "Sala principal · Estudio · Apartamento",
        guarantee: "12 meses",
        featured: true,
        discount: true,
        stock: 5,
        images: [
            "../../assets/img/catalogo/mueble-1.jpg",
            "../../assets/img/catalogo/mueble-2.jpg",
            "../../assets/img/catalogo/mueble-3.jpg",
            "../../assets/img/catalogo/mueble-4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/muebles.jpg"
    },
    {
        id: "prod-aparador-nordico",
        name: "Aparador de madera estilo nórdico",
        price: 1800000,
        compareAtPrice: 1385000,
        category: "dormitorio",
        categoryLabel: "Descanso & Intimidad",
        summary: "Aparador de madera con cajón y puertas, diseño nórdico elegante.",
        summaryDiscount: "¡30% OFF! Aparador nórdico en madera natural.",
        description: "Aparador de madera natural con presencia serena y solución real de guardado. Tiene cajón central, dos módulos laterales y una estética limpia que funciona perfecto en espacios íntimos y de descanso.",
        material: "Madera maciza",
        style: "Nórdico / Escandinavo / Minimalista",
        storage: "1 cajón central + 2 compartimentos",
        idealFor: "Dormitorio · Vestier · Estudio",
        guarantee: "12 meses",
        featured: true,
        discount: true,
        stock: 4,
        images: [
            "../../assets/img/catalogo/mesa-1.jpg",
            "../../assets/img/catalogo/mesa-2.jpg",
            "../../assets/img/catalogo/mesa-3.jpg",
            "../../assets/img/catalogo/mesa-4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/banner-silla.jpg"
    },
    {
        id: "prod-comedor-ratan",
        name: "Mesa redonda con sillas de ratán",
        price: 1200000,
        compareAtPrice: 1000000,
        category: "comedor",
        categoryLabel: "Comedor & Reunión",
        summary: "Mesa redonda con 4 sillas de ratán, ideal para espacios modernos.",
        summaryDiscount: "¡20% OFF! Comedor con sillas de ratán incluido.",
        description: "Set de comedor con mesa redonda en madera clara y cuatro sillas de ratán tejidas. Equilibra comodidad, luz y calidez para cocinas abiertas o comedores compactos.",
        material: "Madera maciza + ratán natural",
        style: "Costero / Escandinavo",
        storage: "No incluye almacenamiento adicional",
        idealFor: "Comedor · Cocina abierta · Apartamento",
        guarantee: "12 meses",
        featured: true,
        discount: true,
        stock: 6,
        images: [
            "../../assets/img/catalogo/comedor2-1.jpg",
            "../../assets/img/catalogo/comedor2-2.jpg",
            "../../assets/img/catalogo/comedor2-3.jpg",
            "../../assets/img/catalogo/comedor2-4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/muebles.jpg"
    },
    {
        id: "prod-mesa-organica",
        name: "Mesa de centro orgánica",
        price: 890000,
        compareAtPrice: 774000,
        category: "sala",
        categoryLabel: "Sala & Descanso",
        summary: "Mesa de centro en madera clara con curva orgánica y acabado suave.",
        summaryDiscount: "¡15% OFF! Mesa de centro orgánica en madera clara",
        description: "Mesa de centro de inspiración orgánica pensada para salas con estilo natural. Combina presencia escultórica y practicidad para acompañar sofás y textiles neutros.",
        material: "Madera clara",
        style: "Orgánico / Japandi",
        storage: "Superficie amplia",
        idealFor: "Sala · Lobby · Estudio",
        guarantee: "12 meses",
        featured: false,
        discount: false,
        stock: 8,
        images: [
            "../../assets/img/catalogo/mesa-1.jpg",
            "../../assets/img/catalogo/mesa-2.jpg",
            "../../assets/img/catalogo/mesa-3.jpg",
            "../../assets/img/catalogo/mesa-4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/banner-silla.jpg"
    },
    {
        id: "prod-sillon-acento",
        name: "Sillón de acento terracota",
        price: 980000,
        compareAtPrice:890000,
        category: "sala",
        categoryLabel: "Sala & Descanso",
        summary: "Sillón de acento envolvente para lectura y descanso.",
        summaryDiscount: "¡Oferta especial! Sillón terracota con 10% OFF.",
        description: "Sillón individual con respaldo envolvente y presencia cálida. Es ideal para sumar un punto focal a cualquier sala o rincón de lectura sin recargar el ambiente.",
        material: "Madera + tapizado premium",
        style: "Contemporáneo / Cálido",
        storage: "No aplica",
        idealFor: "Sala · Rincón de lectura",
        guarantee: "12 meses",
        featured: false,
        discount: false,
        stock: 3,
        images: [
            "../../assets/img/catalogo/silla-tapizada-1.jpg",
            "../../assets/img/catalogo/silla-tapizada-2.jpg",
            "../../assets/img/catalogo/silla-tapizada-3.jpg",
            "../../assets/img/catalogo/silla-tapizada-4.jpg"
        ],
        footerImage: "../../assets/img/bnFooter_infoCatalogo/banner-silla-tapizada.jpg"
    }
];